// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebfrwtddcrkyxqutaywm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImViZnJ3dGRkY3JreXhxdXRheXdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5ODkzNjksImV4cCI6MjA4NjU2NTM2OX0.Rs8VmUZCRHlb0QwJesYNWak0gIxDpf5uvoKg3rCny2w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});